### ISSUE TITLE
Random latitude ?

### ISSUE THREAD

**Issue by Fil** [d3/d3-random#24]
randomLatitude = r => acos(2*r - 1) would be quite useful, probably with a range of [-90,90] by default.

I had also thought of randomGeoPoint = (r1, r2) => [ -180 + 360 * r1, randomLatitude(r2) ] ; but it feels a bit awkward as it would not be a 1d distribution — maybe it should belong to d3-geo instead.

**Comment by mbostock** [comment]
It feels a little weird to just have a stand-alone random for generating a random latitude (and not longitude). But also there’s the question of radians and degrees.

And also, in some cases you might want to use blue noise (Poisson disc in stereographic coordinates?) rather than uniform random white noise.

**Comment by Fil** [comment]
yep & is easy enough to do without a dedicated function
