### ISSUE TITLE
pretest script fails on windows

### ISSUE THREAD

**Issue by p-v-d-Veeken** [d3/d3-random#8]
When cloning the repo and doing `npm install`, the pretest script fails on windows machines. 

npm-debug.log: https://www.dropbox.com/s/5fxh5u7t0omeq7h/npm-debug.log?dl=0

Additional information: 
- OS: Windows 8.1 64-bit
- NodeJS version: 5.0.0
- npm version: 3.3.6

**Comment by svanschooten** [comment]
:+1: verified in git-bash, win-bash and cygwin

**Comment by mbostock** [comment]
I do not have a Windows machine, so unfortunately I have no way of reproducing this issue. However, I suspect that the failure is caused by the `zip` command. This didn’t need to be run on prepublish, so I’ve moved it to postpublish, and hopefully that means `npm install` now succeeds.

If that’s not the case, please help me out by sending a pull request to fix the issue. I’m afraid I would just be guessing blindly trying to fix it myself!

**Comment by p-v-d-Veeken** [comment]
It still crashes in the exact same way as before your fix. I'll have a look at it and try to fix it. No promises though. :)

**Comment by mbostock** [comment]
Sorry, I tried!

Does 'npm test' fail? If so, I’d look at the tests or the test framework
(faucet and tape). If not, the problem might reside in UglifyJS. I can’t
think of much in this library that would be OS-dependent.

**Comment by p-v-d-Veeken** [comment]
Yeah, I think the problem is somewhere in the pretest script actually. I'll let you know if I work it out.

**Comment by p-v-d-Veeken** [comment]
So I found the problem, which was that windows parsed the embedded quotes inside the pretest script incorrectly, so I changed the script to:

`"pretest": "mkdir -p build && node ./scripts/pretest.js > build/version.js && rollup -f umd -n d3_random -o build/d3-random.js -- index.js" `

Which sort of worked, however, my terminal windows now hangs indefinitely on: 

`> d3-random@0.2.1 test C:\Users\Pepe\dropbox\workspace\d3-random`
``> faucet `find test -name '*-test.js'` && eslint index.js src``

Not sure what that is about...

P.S shouldn't this issue be reopened?
